[package]
name = "rustraint"
description = "Rustraint is client for Rustraintd"
version.workspace = true
edition.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true

[[bin]]
name = "rustraint"
path = "src/client.rs"

[dependencies]
clap = { version = "4.6.0", features = ["derive"] }
quick-xml = { version = "0.39.2", features = ["serialize"] }
serde = { version = "1", features = ["derive"] }
